spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    username: ${USERNAME:postgres}
    password: ${PASSWORD:204615}
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/error_manager}

authorization:
  email: ${USER_EMAIL:admin@admin.com}
  firstname: ${FIRST_NAME:Administrador}
  lastname: ${LAST_NAME:Administrador}
  password: ${USER_PASSWORD:admin}
  client:
    id: ${CLIENT_ID:client-id}
    secret: ${CLIENT_SECRET:client-secret}
    grant-types: ${CLIENT_GRANT_TYPES:password, authorization_code, refresh_token}
    scopes: ${CLIENT_SCOPES:any}

swagger:
  title: Error Manager
  description: Projeto para obtenção de certicado de Java na Aceleração da Conta Azul pela Condenation
  version: 1.0
  terms-of-service-url: N/A
  contact:
    name: Grupo 3
    url: https://github.com/luc-zago/api-java-codenation
    email: N/A
  licence: MIT licence
  licence-url: https://mit-license.org/
